language: python
python:
  - "3.5"
before_install:
  - python "$TRAVIS_BUILD_DIR/setup.py" install
  - echo 'yes' | sudo add-apt-repository ppa:ondrej/php
  - sudo apt-get update -qq
  - sudo apt-get install -qq php5-cli php5-curl php5-memcached php5-imagick php5-dev php-pear
  - yes '' | sudo pecl install mongo
  - echo "extension=mongo.so" | sudo tee /etc/php5/cli/php.ini
  - php -v
  - curl https://getcomposer.org/installer | php
  - chmod +x composer.phar
  - sudo ln -s "$PWD/composer.phar" /usr/local/bin/composer
services:
  - mongodb
script:
  - "$TRAVIS_BUILD_DIR/imboclient/test/travis.sh"

